Fix install-githooks, add note about fetch-depth

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -23,7 +23,13 @@ runs:
   steps:
     - run: |
         if git rev-parse --is-shallow-repository; then
-          git fetch origin ${GITHUB_REF_NAME} --unshallow || git fetch origin ${GITHUB_REF_NAME} --depth=10
+          status=0
+          git fetch origin ${GITHUB_REF_NAME} --unshallow || git fetch origin ${GITHUB_REF_NAME} --depth=10 || status=$?
+          if [ $status -ne 0 ]; then
+            echo "Failed to fetch the full history of the repository"
+            echo "Try adding 'fetch-depth: 0' to your checkout action."
+            exit 1
+          fi
         fi
       shell: bash
     - run: ./scripts/action.sh
