Improve tool installation, dockerize (#8)
* Fix ruby

* Ignore lock

* GNU Parallel

* Install uncrustify

* Use asdf

* prettier output

* Update changelog

* Install tools

* Dockerize

* Fix python build

* Use lockfiles

* Fix some tests

* Fix docker + mkdir

* Fix docker

* Fix docker and tests

* prettier and eslint as separate steps

* Fix many tests

* fix tests

* Fix tests

* Use existing temp dir

* Run tests in tools

* lint

* No clippy

* Docker improvements

* env vars

* Remove test

* runs-on

* fix

* fix

* fix

* Lint w docker

* just docker

* workflow

* rm build-docker.sh

* entrypoint

* Fix path

* Fix eslint plugin resolution

* host.docker.internal

* insecure registry

* Simplify build

* set LINTBALL_DIR

* shellcheck

* Optimize docker build, fix parallel test execution

* Fix path

* reshim

* Fix test image

* enable experimental features

* buildx ls

* push

* disable

* Optimize binary file handling

* fix tests

* safer find run

* Fix test

* Simplify binary file check

* Optimizations - use `read` where possible

* Fix tests

* Bump versions

* Copypaste issue

* Upgrades

* Fix prettier

* Bump tool versions, fix some tests

* Fix tests

* Fix test

* Fix docker

* Fix shfmt

* Fix tests

* Fix tests

* Fix docker build

* Reduce duplicate builds

* Fix docker

* Don’t test as part of docker deploy

* Better tagging/caching for docker build

* Less noise in output

* Docker improvements

* Update action.sh

* Get docker + tests working, remove some tools

* Fix action

* fetch

* No pipefail

* git show-ref

* Fetch depth 0

* unshallow

* Improve fetch

* Remove dash, fix pre-commit tests

* Fix cleanup script, debug mount

* Fix git dir

* Check if is in a git worktree and if commit exists

* Smaller docker image, ensure .git is copied

* debug .git dir and env

* which git

* docker tags

* Permissions workaround

* Remove debug code

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,32 +1,21 @@
 #!/usr/bin/env bash
 
-set -ueo pipefail
+# Run lintball using Docker on git commit
 
-if [ -z "${LINTBALL_DIR:-}" ]; then
-  if [ -f "${PWD}/bin/lintball" ]; then
-    # lintball itself
-    LINTBALL_DIR="${PWD}"
-    export LINTBALL_DIR
-  elif [ -f "${PWD}/node_modules/lintball/bin/lintball" ]; then
-    # lintball installed via npm locally
-    LINTBALL_DIR="${PWD}/node_modules/lintball"
-    export LINTBALL_DIR
-  fi
-fi
+set -eu
 
-if [ -n "${LINTBALL_DIR:-}" ]; then
-  "${LINTBALL_DIR}/bin/lintball" pre-commit
-elif [ -n "$(command -v lintball)" ]; then
-  lintball pre-commit
-else
-  {
-    echo
-    echo "Error: could not find a lintball executable, but lintball's pre-commit hook is enabled."
-    echo
-    echo "Install lintball with:"
-    echo
-    echo '  npm install lintball'
-    echo
-  } >&2
+workspace=$(git rev-parse --show-toplevel || true)
+if [[ -z ${workspace} ]]; then
+  echo "Could not determine git repository path" >&2
   exit 1
 fi
+
+if [[ -f "${workspace}/scripts/build-local-docker-image.sh" ]]; then
+  # This is lintball itself, build and use the local image
+  "${workspace}/scripts/build-local-docker-image.sh"
+  image=lintball:local
+else
+  image=elijahru/lintball:latest
+fi
+
+docker run -v "${workspace}:/workspace" "${image}" lintball pre-commit
